name: Perform checks

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/*.yaml'
      - '.github/CODEOWNERS'
      - '.github/pull_request_template.md'
      - 'docs/**/*.md'
      - 'mkdocs.yml'
      - 'README.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/*.yaml'
      - '.github/CODEOWNERS'
      - '.github/pull_request_template.md'
      - 'docs/**/*.md'
      - 'mkdocs.yml'
      - 'README.md'

env:
  PIP_PROGRESS_BAR: "off"
  PIP_DISABLE_PIP_VERSION_CHECK: "on"

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.12', '3.13', '3.14' ] # Define Python versions here

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run Pytest
        run: |
          uv run pytest
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run ruff check
        run: uv run ruff check

      - name: Run ruff format check
        run: uv run ruff format --check .

  integration-tests:
    runs-on: ubuntu-latest

    env:
      TESTCONTAINER_DOCKER_NETWORK: kcwarden-integration-test-network

    steps:
      - name: Create Docker network for running Testcontainers
        run: docker network create ${{ env.TESTCONTAINER_DOCKER_NETWORK }}

      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run integration tests
        run: uv run pytest --integration
