name: Deploy documentation

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest
    env:
      PIP_PROGRESS_BAR: "off"
      PIP_DISABLE_PIP_VERSION_CHECK: "on"
    container:
      image: python:3.13-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install MkDocs
        run: pip install mkdocs

      - name: Build
        run: mkdocs build

      - name: Create Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    runs-on: ubuntu-latest

    # Add a dependency to the build job
    needs: build-docs

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4

